on: push

name: Create Release

jobs:
  build:
    name: Add new release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        ./build.sh
    - name: Commit new standalone lib
      uses: EndBug/add-and-commit@v4
      with:
        message: "Standalone lib"
        add: "."
        tag: "v0.5"
    - name: Checkout code for release
      uses: actions/checkout@v2
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  tag: 'v0.5'
